import assert from 'node:assert/strict';
import {grouped,renderChart,escapeHTML,number} from '../assets/charts.js';
const q={kind:'number',min:0,max:10,view:'bars',options:[]};
const bins=grouped(q,[0,1,5,10]);
assert.equal(bins.reduce((n,b)=>n+b.count,0),4);
assert.equal(bins[0].count,1);assert.equal(bins[9].count,1);
const decimals=grouped({...q,min:0,max:0.001},[0,0.0001,0.0005,0.001]);
assert.equal(new Set(decimals.map(bin=>bin.label)).size,10,'Small decimal ranges need distinct, readable labels.');
assert.equal(decimals[1].count,1,'An exact boundary belongs to the interval starting at that value.');
assert.equal(decimals[9].count,1,'The maximum belongs to the final interval.');
assert.equal(grouped({...q,min:0.1,max:1.1},[0.3])[2].count,1,'Decimal arithmetic must agree with displayed interval boundaries.');
assert.deepEqual(grouped({kind:'scale',min:1,max:3},[1,2,2,3]).map(bin=>bin.count),[1,2,1]);
assert.equal(grouped({kind:'ranking',options:['A','B']},[['A','B'],['B','A']])[0].count,1.5,'Ranking reports average placement.');
assert.equal(number(0.0001),'0,0001');
const tiny=grouped({...q,min:1,max:1+Number.EPSILON},[1,1+Number.EPSILON]);
assert.equal(tiny.length,1,'Do not draw zero-width intervals for adjacent floating-point values.');
assert.equal(tiny[0].count,2);
assert.ok(tiny[0].label.includes('1,0000000000000002'));
assert.equal(grouped(q,[NaN,Infinity,'5',-1,11]).reduce((total,bin)=>total+bin.count,0),0);
assert.deepEqual(grouped({...q,min:10,max:10},[10]),[]);
assert.equal(grouped({kind:'check',options:['A','B']},[['A','B'],['A']])[0].count,2);
assert.deepEqual(grouped({kind:'word'},['Å','å','å']),[{label:'å',count:3}]);
assert.ok(escapeHTML('<img src=x onerror=alert(1)>').startsWith('&lt;img'));
assert.ok(!renderChart({kind:'sentence',view:'cards'},['<script>alert(1)</script>']).includes('<script>'));
assert.ok(renderChart({kind:'number',min:-5,max:5,view:'thermo'},[-5,0,5]).includes('Medelvärde'));
assert.ok(renderChart({kind:'number',min:0,max:10,view:'bars'},[4,5,6]).includes('Konvergens'));
assert.ok(renderChart({kind:'choice',options:['A','B'],view:'pie'},['A','B']).includes('conic-gradient'));
assert.ok(renderChart({kind:'choice',options:['A','B'],view:'pie'},['A','A','B']).includes('Svarspuls'));
assert.ok(renderChart({kind:'ranking',options:['A','B'],view:'bars'},[['A','B'],['B','A']]).includes('ranking-race'));
assert.ok(renderChart({kind:'matrix',options:{rows:['R1'],columns:['Nej','Ja']},view:'matrix'},[{'R1':'Ja'}]).includes('Ja'));
assert.ok(renderChart({kind:'sentence',view:'cards'},['Snabba möten fungerar','Snabba möten hjälper','Långa möten tröttar']).includes('Återkommande teman'));
assert.ok(renderChart(q,[]).includes('Inga svar ännu'));
console.log('PASS: histogram boundaries, multi-select counts, Unicode grouping, HTML escaping, thermometer, pie and empty results.');
