<?php
declare(strict_types=1);
// Included by integration.php; shares its isolated accounts, clients and cleanup.
if (!isset($owner,$db,$prefix)) {fwrite(STDERR,"Kör tests/integration.php.\n");exit(1);}
function createTestSet(string $progression,int $size=3): array {
    global $owner,$prefix,$created,$db;
    $questions=[];
    for($i=0;$i<$size;$i++) $questions[]=['title'=>$prefix.' fråga '.($i+1),'kind'=>'yesno','options'=>[],'view'=>'pie'];
    $code=request($owner,'create-set',['title'=>$prefix.' set','progression'=>$progression,'questions'=>$questions],[],201)['code'];
    $created[]=$code;
    $stmt=$db->prepare('SELECT q.code FROM puls_set_questions m JOIN puls_questions root ON root.id=m.set_id JOIN puls_questions q ON q.id=m.question_id WHERE root.code=?');
    $stmt->bind_param('s',$code);$stmt->execute();
    foreach($stmt->get_result()->fetch_all(MYSQLI_ASSOC) as $row)$created[]=$row['code'];
    return request($owner,'results',null,['code'=>$code]);
}
request($voter,'create-set',[],[],401);
request($owner,'create-set',[],[],403,'invalid');
request($owner,'create-set',['title'=>'Invalid','progression'=>'host','questions'=>[]],[],400);
$auto=createTestSet('automatic');$setCode=$auto['set']['code'];$ids=array_column($auto['questions'],'id');
$second=client();request($second,'bootstrap');
$state=request($voter,'question',null,['code'=>$setCode]);
check($state['question']['id']===$ids[0] && $state['set']['total']===3,'Automatic set opens at first unanswered question');
request($voter,'answer',['value'=>'Ja'],['code'=>$setCode],400);
request($voter,'answer',['questionId'=>$ids[1],'value'=>'Ja'],['code'=>$setCode],409);
request($voter,'answer',['questionId'=>$ids[0],'value'=>'Ja'],['code'=>$setCode],201);
check(request($voter,'question',null,['code'=>$setCode])['question']['id']===$ids[1],'Automatic participant advances on the same code');
check(request($second,'question',null,['code'=>$setCode])['question']['id']===$ids[0],'Another participant has independent progress');
check(request($voter,'answer',['questionId'=>$ids[0],'value'=>'Nej'],['code'=>$setCode])['already'],'Late duplicate does not answer the next question');
check(request($owner,'results',null,['code'=>$setCode,'questionId'=>$ids[1]])['answers']===[],'Duplicate answer leaves next question unanswered');
request($owner,'update',['open'=>false],['code'=>$setCode]);
request($voter,'answer',['questionId'=>$ids[1],'value'=>'Ja'],['code'=>$setCode],409);
check(!request($second,'question',null,['code'=>$setCode])['question']['open'],'Pausing a set applies to every participant position');
request($owner,'update',['open'=>true],['code'=>$setCode]);
foreach([$ids[1],$ids[2]] as $qid)request($voter,'answer',['questionId'=>$qid,'value'=>'Nej'],['code'=>$setCode],201);
check(request($voter,'question',null,['code'=>$setCode])['complete'],'Automatic set completes after all answers');
check(request($voter,'question',null,['code'=>$setCode])['complete'],'Completed progress survives repeat loads');
request($owner,'set-advance',['position'=>0],['code'=>$setCode],409);
request($nonOwner,'results',null,['code'=>$setCode],403);
request($nonOwner,'update',['open'=>false],['code'=>$setCode],403);
request($nonOwner,'delete',[],['code'=>$setCode],403);
$list=request($owner,'list')['questions'];$listed=array_values(array_filter($list,static fn($q)=>$q['code']===$setCode));
check(count($listed)===1 && $listed[0]['kind']==='set' && (int)$listed[0]['question_count']===3 && (int)$listed[0]['answer_count']===3,'Owner list groups all set questions and answer counts');
$internalCode=$db->query('SELECT code FROM puls_questions WHERE id='.(int)$ids[1])->fetch_assoc()['code'];
check(!in_array($internalCode,array_column($list,'code'),true),'Internal member questions are not listed separately');
request($voter,'question',null,['code'=>$internalCode],404);
request($voter,'answer',['value'=>'Ja'],['code'=>$internalCode],404);
request($owner,'results',null,['code'=>$setCode,'questionId'=>0],400);
request($owner,'update',['questionId'=>$ids[1],'view'=>'bars'],['code'=>$setCode]);
check(request($owner,'results',null,['code'=>$setCode,'questionId'=>$ids[1]])['question']['view']==='bars','Result view can change independently per set question');

$host=createTestSet('host');$hostCode=$host['set']['code'];$hostIds=array_column($host['questions'],'id');
request($owner,'results',null,['code'=>$hostCode,'questionId'=>$ids[0]],400);
request($voter,'answer',['questionId'=>$hostIds[1],'value'=>'Ja'],['code'=>$hostCode],409);
request($voter,'answer',['questionId'=>$hostIds[0],'value'=>'Ja'],['code'=>$hostCode],201);
$waiting=request($voter,'question',null,['code'=>$hostCode]);
check($waiting['waiting'] && !$waiting['complete'],'Host mode waits after a saved answer');
request($owner,'results',null,['code'=>$hostCode,'questionId'=>$hostIds[2]]);
check(request($voter,'question',null,['code'=>$hostCode])['question']['id']===$hostIds[0],'Viewing another result does not advance participants');
request($nonOwner,'set-advance',['position'=>0],['code'=>$hostCode],403);
request($owner,'set-advance',null,['code'=>$hostCode],405);
request($owner,'set-advance',['position'=>0],['code'=>$hostCode]);
request($owner,'set-advance',['position'=>0],['code'=>$hostCode],409);
check(request($voter,'question',null,['code'=>$hostCode])['question']['id']===$hostIds[1],'Host advances exactly one question, including on repeated clicks');
request($second,'answer',['questionId'=>$hostIds[0],'value'=>'Ja'],['code'=>$hostCode],409);
check(request($second,'question',null,['code'=>$hostCode])['question']['id']===$hostIds[1],'Late participants join the currently visible host question');
request($owner,'update',['open'=>false],['code'=>$hostCode]);
request($owner,'set-advance',['position'=>1],['code'=>$hostCode]);
check(!request($voter,'question',null,['code'=>$hostCode])['question']['open'],'Advancing while paused keeps the set paused');
request($owner,'update',['open'=>true],['code'=>$hostCode]);
request($voter,'answer',['questionId'=>$hostIds[2],'value'=>'Ja'],['code'=>$hostCode],201);
check(request($voter,'question',null,['code'=>$hostCode])['complete'],'Answering the final host question completes participation');
request($owner,'set-advance',['position'=>2],['code'=>$hostCode]);
check(request($second,'question',null,['code'=>$hostCode])['complete'],'Finishing the set releases waiting and unanswered participants');
request($second,'answer',['questionId'=>$hostIds[2],'value'=>'Ja'],['code'=>$hostCode],409);
$single=createTestSet('automatic',1);$singleCode=$single['set']['code'];
request($voter,'answer',['questionId'=>$single['question']['id'],'value'=>'Ja'],['code'=>$singleCode],201);
check(request($voter,'question',null,['code'=>$singleCode])['complete'],'A one-question set works');
$png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j/pkAAAAASUVORK5CYII=';
$design=['colors'=>['background'=>'#e8f0e9','surface'=>'#ffffff','text'=>'#173d2a','primary'=>'#276847'],'images'=>['background'=>$png,'foreground'=>$png,'logo'=>$png]];
request($nonOwner,'set-design',$design,['code'=>$hostCode],403);
request($owner,'set-design',$design,['code'=>$hostCode],403,'invalid');
request($owner,'set-design',null,['code'=>$hostCode],405);
$saved=request($owner,'set-design',$design,['code'=>$hostCode])['design'];
check(count($saved['images'])===3 && !str_contains(json_encode($saved),'base64'),'Design response uses image URLs, not repeated image bytes');
check(request($second,'question',null,['code'=>$hostCode])['set']['design']===$saved,'Participants receive the saved set design');
check(request($owner,'results',null,['code'=>$setCode])['set']['design']===null,'A different set keeps its own appearance');
request($owner,'set-design',['images'=>['logo'=>'bad']],['code'=>$hostCode],400);
check(request($owner,'results',null,['code'=>$hostCode])['set']['design']===$saved,'Rejected design does not overwrite the previous design');
$kept=request($owner,'set-design',['colors'=>$design['colors'],'images'=>['logo'=>'keep']],['code'=>$hostCode])['design'];
check(array_keys($kept['images'])===['logo'] && $kept['version']!==$saved['version'],'Existing logo retained while other images are removed');
$curl=curl_init($base.'/'.$kept['images']['logo']);curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);$image=curl_exec($curl);
check(curl_getinfo($curl,CURLINFO_RESPONSE_CODE)===200 && curl_getinfo($curl,CURLINFO_CONTENT_TYPE)==='image/png' && $image===base64_decode(explode(',',$png)[1]),'Image endpoint serves the stored bytes with the correct MIME type');curl_close($curl);
request($owner,'set-design',['colors'=>null,'images'=>[]],['code'=>$hostCode]);
request($second,'set-image',null,['code'=>$hostCode,'slot'=>'logo'],404);
check(true,'Set design reset removes uploaded images');
foreach([[$setCode,$ids],[$hostCode,$hostIds],[$singleCode,[$single['question']['id']]]] as [$removeCode,$removeIds]){
    request($owner,'delete',[],['code'=>$removeCode]);
    request($voter,'question',null,['code'=>$removeCode],404);
    $idsSql=implode(',',array_map('intval',$removeIds));
    check((int)$db->query('SELECT COUNT(*) AS n FROM puls_questions WHERE id IN ('.$idsSql.')')->fetch_assoc()['n']===0,'Deleting a set removes every member question');
    check((int)$db->query('SELECT COUNT(*) AS n FROM puls_answers WHERE question_id IN ('.$idsSql.')')->fetch_assoc()['n']===0,'Deleting a set cascades to every answer');
}
check(true,'Question-set HTTP checks passed');
