<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/validation.php';
require dirname(__DIR__).'/includes/set-design.php';
function check(bool $condition,string $name): void {if(!$condition)throw new RuntimeException('FAIL: '.$name);echo "OK: $name\n";}
function rejects(callable $fn,string $name): void {try{$fn();}catch(InvalidArgumentException $e){check(true,$name);return;}throw new RuntimeException('FAIL: '.$name);}
$p=['title'=>'Vad tycker du?','kind'=>'choice','options'=>['Öva','Prata'],'min'=>0,'max'=>10,'view'=>'bars'];
check(validate_question($p)['options']===['Öva','Prata'],'Swedish options');
rejects(fn()=>validate_question(array_replace($p,['options'=>['Öva','öva']])),'Case-insensitive duplicate options');
rejects(fn()=>validate_question(array_replace($p,['view'=>'cloud'])),'Incompatible chart rejected');
$n=validate_question(array_replace($p,['kind'=>'number','min'=>-2.5,'max'=>2.5,'view'=>'thermo']));
check($n['min']===-2.5,'Decimal and negative range');
$q=['kind'=>'number','options_json'=>'[]','min_value'=>-2.5,'max_value'=>2.5];
check(validate_answer($q,0)===0,'Zero is a valid value');
rejects(fn()=>validate_answer($q,'0'),'String instead of number');
rejects(fn()=>validate_answer($q,3),'Out of range');
$scale=validate_question(['title'=>'Hur känns det?','kind'=>'scale','options'=>[],'min'=>1,'max'=>5,'view'=>'bars']);
check($scale['kind']==='scale' && validate_answer(['kind'=>'scale','options_json'=>'[]','min_value'=>1,'max_value'=>5],3)===3,'Scale accepts integer steps');
rejects(fn()=>validate_answer(['kind'=>'scale','options_json'=>'[]','min_value'=>1,'max_value'=>5],3.5),'Scale rejects fractional steps');
$ranking=validate_question(['title'=>'Vad är viktigast?','kind'=>'ranking','options'=>['A','B','C'],'min'=>0,'max'=>10,'view'=>'bars']);
check(validate_answer(['kind'=>'ranking','options_json'=>'["A","B","C"]'],['C','A','B'])===['C','A','B'],'Ranking preserves order');
rejects(fn()=>validate_answer(['kind'=>'ranking','options_json'=>'["A","B","C"]'],['A','A','B']),'Ranking rejects duplicate choices');
$matrix=validate_question(['title'=>'Bedöm påståendena','kind'=>'matrix','options'=>['rows'=>['R1','R2'],'columns'=>['Nej','Ja']],'min'=>0,'max'=>10,'view'=>'matrix']);
check($matrix['options']['columns']===['Nej','Ja'],'Matrix stores rows and columns');
check(validate_answer(['kind'=>'matrix','options_json'=>'{"rows":["R1","R2"],"columns":["Nej","Ja"]}'],['R1'=>'Ja','R2'=>'Nej'])===['R1'=>'Ja','R2'=>'Nej'],'Matrix preserves row answers');
$designQuestion=validate_set_design(['colors'=>['background'=>'#f4f5f9','surface'=>'#ffffff','text'=>'#20213a','primary'=>'#4941ce'],'images'=>[]]);
check($designQuestion['colors']['primary']==='#4941ce','Question design uses the shared appearance contract');
$q=['kind'=>'check','options_json'=>'["A","B"]'];
check(validate_answer($q,['A','B'])===['A','B'],'Multiple choices');
rejects(fn()=>validate_answer($q,['A','A']),'Duplicate checkbox choices');
rejects(fn()=>validate_answer($q,['C']),'Unknown choice');
$q=['kind'=>'word','options_json'=>'[]'];
check(validate_answer($q,' nyfiken ')==='nyfiken','Word trimmed');
rejects(fn()=>validate_answer($q,'två ord'),'Multiple words rejected');
rejects(fn()=>validate_answer($q,str_repeat('å',41)),'Unicode length limit');
$q=['kind'=>'sentence','options_json'=>'[]'];
check(validate_answer($q,'<script>alert(1)</script>')==='<script>alert(1)</script>','Text preserved; frontend must escape it');
rejects(fn()=>validate_question(array_replace($p,['title'=>"invalid\xFF"])),'Invalid UTF-8 rejected');
rejects(fn()=>validate_question(array_replace($p,['title'=>"hidden\0text"])),'NUL in text rejected');
rejects(fn()=>validate_question(array_replace($p,['kind'=>'number','min'=>-INF,'max'=>10,'view'=>'bars'])),'Infinite range rejected');
check(validate_email(' PERSON@Example.COM ')==='person@example.com','Email normalized for account uniqueness');
rejects(fn()=>validate_email('person@example.com,other@example.com'),'Multiple email addresses rejected');
rejects(fn()=>validate_email([]),'Non-string email rejected');
check(validate_registration(['name'=>' Åsa ','email'=>'asa@example.com','password'=>'ett långt lösenord'])['name']==='Åsa','Unicode account name preserved');
rejects(fn()=>validate_registration(['name'=>'','email'=>'asa@example.com','password'=>'ett långt lösenord']),'Empty account name rejected');
rejects(fn()=>validate_password('kort'),'Short password rejected');
rejects(fn()=>validate_password(str_repeat('å',37)),'Bcrypt byte limit respected');
rejects(fn()=>validate_password("abcdefghij\0rest"),'Password NUL rejected');
check(validate_password(str_repeat('å',36))===str_repeat('å',36),'Password at byte boundary accepted');
$tokens=['bg'=>'#F9F9F9','surface'=>'#ffffff','text'=>'#222222','primary'=>'#123456','primary-contrast'=>'#ffffff'];
$theme=['name'=>' Mitt tema ','light'=>$tokens,'dark'=>array_replace($tokens,['bg'=>'#111111','text'=>'#eeeeee'])];
check(validate_theme($theme)['light']['bg']==='#f9f9f9','Theme colors normalized');
check(validate_theme($theme)['name']==='Mitt tema','Theme name trimmed');
check(validate_theme(null)===null,'Theme can be reset');
check(validate_theme(array_replace($theme,['light'=>$tokens+['font-body'=>'"Open Sans", sans-serif','radius-sm'=>'6.25px']]))['light']['radius-sm']==='6.25px','Safe theme fonts and radii accepted');
rejects(fn()=>validate_theme(array_replace($theme,['light'=>['bg'=>'#ffffff']])),'Incomplete theme rejected');
rejects(fn()=>validate_theme($theme+['css'=>'body{display:none}']),'Unrecognized theme fields rejected');
rejects(fn()=>validate_theme(array_replace($theme,['light'=>array_replace($tokens,['bg'=>'url(https://example.com/tracker)'])])),'CSS URL rejected');
rejects(fn()=>validate_theme(array_replace($theme,['light'=>$tokens+['font-body'=>'sans-serif;display:none']])),'CSS declaration injection rejected');
rejects(fn()=>validate_theme(array_replace($theme,['light'=>$tokens+['radius-sm'=>'99px']])),'Oversized theme radius rejected');
rejects(fn()=>validate_theme(array_replace($theme,['light'=>$tokens+['position'=>'fixed']])),'Unknown theme token rejected');
$set=['title'=>'Dagens frågor','progression'=>'automatic','questions'=>[$p]];
check(count(validate_question_set($set)['questions'])===1,'A question set may contain one question');
check(validate_question_set(array_replace($set,['progression'=>'host']))['progression']==='host','Host-controlled progression accepted');
check(count(validate_question_set(array_replace($set,['questions'=>array_fill(0,20,$p)]))['questions'])===20,'Twenty questions accepted');
rejects(fn()=>validate_question_set(array_replace($set,['questions'=>[]])),'Empty set rejected');
rejects(fn()=>validate_question_set(array_replace($set,['questions'=>array_fill(0,21,$p)])),'Oversized set rejected');
rejects(fn()=>validate_question_set(array_replace($set,['questions'=>['key'=>$p]])),'Non-list questions rejected');
rejects(fn()=>validate_question_set(array_replace($set,['questions'=>[null]])),'Malformed set question rejected');
rejects(fn()=>validate_question_set(array_replace($set,['questions'=>[array_replace($p,['title'=>''])]])),'Invalid nested question rejected');
rejects(fn()=>validate_question_set(array_replace($set,['title'=>''])),'Unnamed set rejected');
rejects(fn()=>validate_question_set(array_replace($set,['progression'=>'invalid'])),'Unknown progression rejected');
$png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j/pkAAAAASUVORK5CYII=';
$design=['colors'=>['background'=>'#FFFFFF','surface'=>'#eeeeee','text'=>'#111111','primary'=>'#446622'],'images'=>['logo'=>$png]];
check(validate_set_design($design)['colors']['background']==='#ffffff','Set colors normalized');
check(validate_set_design($design)['images']['logo']['mime']==='image/png','Valid PNG accepted');
check(validate_set_design(['images'=>['logo'=>'keep']],true)['images']['logo']==='keep','Existing image can be retained');
rejects(fn()=>validate_set_design(['images'=>['logo'=>'keep']]),'Cannot retain an image when creating a set');
rejects(fn()=>validate_set_design(['colors'=>['text'=>'#fff']]),'Incomplete set colors rejected');
rejects(fn()=>validate_set_design(['images'=>['logo'=>'https://example.com/logo.png']]),'External image URLs rejected');
rejects(fn()=>validate_set_design(['images'=>['logo'=>'data:image/svg+xml;base64,'.base64_encode('<svg/>')]]),'SVG uploads rejected');
rejects(fn()=>validate_set_design(['images'=>['logo'=>'data:image/png;base64,'.base64_encode('not an image')]]),'Fake PNG rejected');
rejects(fn()=>validate_set_design(['images'=>['logo'=>str_repeat('x',1400001)]]),'Oversized image rejected');
rejects(fn()=>validate_set_design(['images'=>['other'=>$png]]),'Unknown image slot rejected');
echo "All validation checks passed.\n";
